### ISSUE TITLE
SET_OPENVPN_MANAGEMENT_PORT_LIST a b c d works

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/lc-daemon#11]
https://github.com/letsconnectvpn/lc-daemon/blob/f7e9b1558af11a6fa1a5db2cee2ecc1e6ae0cdc5/lc-daemon/main.go#L78

there is error checking, but it doesn't show errors when you specify invalid ports, e.g. use a character as port... maybe it should give an error if any of the specified ports is not a valid integer and not `0 < port <= 2^16 − 1`. What do you think?

**Comment by auamod** [comment]
Working on it.
These are possible errors:
`ERR: MISSING_PARAMETER`

`ERR: INVALID_PARAMETER` for `0 < port <= 2^16 − 1` , `non-integers`.

What can be done for `duplicate_port_in_portlist`? Show no error but port will not be added to `portlist`?

**Comment by fkooman** [comment]
> What can be done for duplicate_port_in_portlist? Show no error but port will not be added to portlist?

Yeah, that makes sense!
