### ISSUE TITLE
make SET_OPENVPN_MANAGEMENT_PORT_LIST actually SET and not ADD

### ISSUE THREAD

**Issue by fkooman** [letsconnectvpn/lc-daemon#12]
Actually, the SET_OPENVPN_MANAGEMENT_PORT_LIST is currently pretty much ADD_OPENVPN_MANAGEMENT_PORT_LIST. If you run the command multiple times, the ports just keep getting added. Maybe we should turn this into a real SET, i.e. only use the ports that are specified in the latest SET_OPENVPN_MANAGEMENT_PORT_LIST command?

**Comment by auamod** [comment]
Will also fix duplicate ports in https://github.com/letsconnectvpn/lc-daemon/issues/11

**Comment by auamod** [comment]
Was fixed in https://github.com/letsconnectvpn/lc-daemon/pull/14

https://github.com/letsconnectvpn/lc-daemon/blob/b74fe192c01ba300d09ac9c5d3e1c61a87b61c9f/lc-daemon/main.go#L90
If everything is valid, the old one will be overwritten and the new one will be used.
