### ISSUE TITLE
Parse Input SET_OPENVPN_MANAGEMENT_PORT_LIST & DISCONNECT

### ISSUE THREAD

**Issue by auamod** [letsconnectvpn/lc-daemon#28]
Currently this is accepted `SET_OPENVPN_MANAGEMENT_PORT_LIST11490 11491` and `DISCONNECTfoo`.

However we are left with `1490 11491` and `oo`. Should this be addressed?

I was thinking something along the lines of introducing a check for the character after the command, so that it's an actual `SPACE`

**Comment by fkooman** [comment]
maybe yeah, or a full regexp check of the command?! 

    /^SET_OPENVPN_MANAGEMENT_PORT_LIST( [0-9]+)+$/

Still my remark from before counts, now we have two problems!
